server:
  port: 8080
  tomcat:
    relaxedPathChars: "|,{,},[,]"
    relaxedQueryChars: "|,{,},[,]"
  max-http-header-size: 40KB

vas:
  datasource:
    host: localhostt
    user: default
    pass: defaultpassword
  keycloakClientSecret:
  keycloakClientId:
  authentication-url:
    token-url: https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token
    jwk-set-uri: https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/certs
    auth-url: https://centralidp.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/auth


bearer_token:
  bearer_format: JWT
  bearer_schema: bearer

spring:
  application:
    name: value-added-service
  liquibase:
    change-log: classpath:config/liquibase/master.xml
    enabled: true
  security:
    oauth2:
      client:
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            client-id: ${vas_keycloakClientId}
            client-secret: ${vas_keycloakClientSecret}
        provider:
          keycloak:
            token-uri: ${vas.authentication-url.token-url}
      resourceserver:
        jwt:
          jwk-set-uri: ${vas.authentication-url.jwk-set-uri}

  datasource:
    username: vas
    url: jdbc:postgresql://${vas.datasource.host}:5432/vas
    driverClassName: org.postgresql.Driver
    password: ${vas_datasource_pass}
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: public
        show_sql: false
        format_sql: true
        types:
          print:
            banner: false
security:
  enabled: true

logging:
  level:
    root: INFO
    com.catenax.valueaddedservice: DEBUG

application:
  name: default
  host: project-value-added-service-vas/api/dashboard
  partnersPoolUrl:
    legalEntities: 'http://localhost:8080/api/catena/legal-entities'
  clientId: 'Cl16-CX-CRisk'

management:
  endpoints:
    web:
      base-path: /management
      exposure:
        include: ['configprops', 'env', 'health', 'info', 'loggers', 'prometheus', 'threaddump', 'caches']
  endpoint:
    health:
      probes:
        enabled: true
  health:
    db:
      enabled: true
    livenessState:
      enabled: true
    readinessState:
      enabled: true

springdoc:
  swagger-ui:
    oauth:
      client-id: Cl2-CX-Portal

ESAPI:
  Logger: org.owasp.esapi.reference.Log4JLogFactory